name: Deploy games pages
on:
  - workflow_dispatch
permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MOBY_API_KEY: '${{ secrets.MOBY_API_KEY }}'

jobs:
  deploy-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3
          cache: pip
      - name: PIP Dependencies
        run: pip install -r requirements.txt
      - name: Google Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_AUTH }}'
      - name: Cache images
        uses: actions/cache@v3
        with:
          path: images
          key: 
      - name: Create schedule file
        run: python schedule.py
        env:
          SPREADSHEET_ID: '${{ vars.SCHEDULE_SPREADSHEET_ID }}'
          SPREADSHEET_NAME: '${{ vars.SCHEDULE_SPREADSHEET_NAME }}'
          SPREADSHEET_RANGE: '${{ vars.SCHEDULE_SPREADSHEET_RANGE }}'
      - name: Create deployment artifact
        run: |
          chmod -R +rX *.html *.css images
          tar -czvf "$RUNNER_TEMP/artifact.tar.gz" \
            --dereference --hard-dereference --force-local \
            *.html *.css images
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar.gz
          retention-days: 1
          if-no-files-found: error
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4